import dynamic from "next/dynamic";
import Head from "next/head";
import styles from "../styles/Three/scene.module.css"
import Navbar from "@/components/Top/Navbar";
import Hero from '../components/Top/Hero'
import Carousel from "@/components/Carousel/Carousel";
import data from '../Data/Carousel'
import Form from "@/components/Form/form";
import StickySlider from "@/components/Stickyslider";
import Loader from '@/components/Loader';
import { useState } from "react";
import Experience from "@/components/Experience";
import Footer from "@/components/Footer";

const Rose = dynamic(() => import('../components/Three/Rose'), {
  ssr: false,
});
const RoseFull = dynamic(() => import('../components/Three/RoseFull'), {
  ssr: false,
});

export default function Home() {
  const [loading, setLoading] = useState(true);
  return (
    <>
      <Head>
        <title>Pushkar.dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/P.ico" />
      </Head>
<div>
{loading && <Loader />}
    <Navbar />

    <div className={styles.container}>
      <Rose className={styles.rose} setLoading={setLoading}/>
    </div>

    <Hero className={styles.hero} loading={loading}/>

    <div className={styles.center}>
     <Carousel data={data} activeSlide={2} className={styles.carousel}/>
    </div>

    <StickySlider />

    <Experience />

    <div className={styles.container1}>
      <RoseFull className={styles.rose2}/>
      <Form />
    </div>
    <Footer />

</div>
    </>
  );
}
